"use client";

import { useState, useRef, useEffect } from "react";
import { MessageSquare, X, Send, Bot, User, Cloud } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { AnimatePresence, motion } from "framer-motion";

type Message = { id: string; role: "user" | "assistant"; content: string };

export default function ChatCopilot() {
  const [isOpen, setIsOpen] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  
  const [messages, setMessages] = useState<Message[]>([
    { id: "1", role: "assistant", content: "Hi! I'm your ClimateGuard AI Consultant. Ask me anything about your resilience plan or MSME loan eligibility." }
  ]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMessage: Message = { id: Date.now().toString(), role: "user", content: input };
    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput("");
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: newMessages })
      });

      if (!response.ok) {
        throw new Error(await response.text() || "Failed to fetch");
      }

      const reader = response.body?.getReader();
      if (!reader) throw new Error("No response stream");
      const decoder = new TextDecoder();
      
      let assistantMessage = "";
      const assistantId = (Date.now() + 1).toString();
      
      setMessages((prev) => [...prev, { id: assistantId, role: "assistant", content: "" }]);

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        
        // Very basic parsing for Data Stream Protocol chunks like '0:"Hello"\n'
        // or just plain text if it's fallback text stream
        const lines = chunk.split('\n');
        for (const line of lines) {
          if (line.startsWith('0:')) {
            try {
              assistantMessage += JSON.parse(line.slice(2));
            } catch (e) {
              assistantMessage += line.slice(2).replace(/^"|"$/g, '');
            }
          } else if (line.trim()) {
            // fallback plain text handling if it's not the Vercel DSP
            assistantMessage += line;
          }
        }

        setMessages((prev) => 
          prev.map((msg) => msg.id === assistantId ? { ...msg, content: assistantMessage } : msg)
        );
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  const generatePDFReport = async () => {
    try {
      const { jsPDF } = await import("jspdf");
      
      const doc = new jsPDF();
      doc.setFontSize(22);
      doc.setTextColor(236, 72, 153); // Fuchsia
      doc.text("ClimateGuard Resilience Report", 20, 20);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by Satin Finserv AI Consultant", 20, 30);
      
      doc.setDrawColor(236, 72, 153);
      doc.line(20, 35, 190, 35);
      
      let yPos = 45;
      
      messages.forEach((msg) => {
        if (msg.id === "1" || !msg.content.trim()) return; // skip initial or empty
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        
        const sender = msg.role === "user" ? "Client Inquiry:" : "AI Consultant Strategy:";
        doc.text(sender, 20, yPos);
        yPos += 7;
        
        doc.setFont("helvetica", "normal");
        doc.setTextColor(80, 80, 80);
        const splitText = doc.splitTextToSize(msg.content, 170);
        doc.text(splitText, 20, yPos);
        
        yPos += (splitText.length * 6) + 10;
        
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
      });
      
      doc.save("ClimateGuard_Action_Plan.pdf");
    } catch (err) {
      console.error("PDF Gen Error", err);
    }
  };

  return (
    <>
      <AnimatePresence>
        {!isOpen && (
          <motion.div
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0, opacity: 0 }}
            className="fixed bottom-6 right-6 z-50"
          >
            <Button
              onClick={() => setIsOpen(true)}
              className="w-14 h-14 rounded-full bg-gradient-to-r from-fuchsia-600 to-pink-500 hover:from-fuchsia-500 hover:to-pink-400 shadow-[0_0_20px_rgba(236,72,153,0.4)] border-0"
            >
              <Cloud className="w-6 h-6 text-white" />
            </Button>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            transition={{ duration: 0.2 }}
            className="fixed bottom-6 right-6 z-50 w-80 md:w-96 shadow-2xl"
          >
            <Card className="bg-[#0c0c10]/95 border-fuchsia-500/20 backdrop-blur-xl shadow-[0_10px_40px_rgba(0,0,0,0.5)] flex flex-col h-[500px] overflow-hidden">
              
              {/* Header */}
              <div className="flex items-center justify-between p-4 border-b border-white/10 bg-gradient-to-r from-fuchsia-900/20 to-transparent">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-fuchsia-500/20 flex items-center justify-center">
                    <Bot className="w-4 h-4 text-fuchsia-400" />
                  </div>
                  <div>
                    <h3 className="font-bold text-white text-sm">Climate Copilot</h3>
                    <p className="text-xs text-zinc-400">Powered by AI</p>
                  </div>
                </div>
                <div className="flex items-center gap-1">
                  {messages.length > 1 && (
                    <Button variant="ghost" size="icon" onClick={generatePDFReport} title="Download Report" className="text-zinc-400 hover:text-fuchsia-400 hover:bg-fuchsia-500/10 rounded-full h-8 w-8">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                    </Button>
                  )}
                  <Button variant="ghost" size="icon" onClick={() => setIsOpen(false)} className="text-zinc-400 hover:text-white hover:bg-white/10 rounded-full h-8 w-8">
                    <X className="w-4 h-4" />
                  </Button>
                </div>
              </div>

              {/* Messages */}
              <div className="flex-1 overflow-y-auto p-4 space-y-4">
                {messages.map((msg) => (
                  <div key={msg.id} className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${msg.role === "user" ? "bg-zinc-800" : "bg-fuchsia-500/20"}`}>
                      {msg.role === "user" ? <User className="w-4 h-4 text-zinc-300" /> : <Bot className="w-4 h-4 text-fuchsia-400" />}
                    </div>
                    <div className={`p-3 rounded-2xl max-w-[80%] text-sm ${
                      msg.role === "user" 
                        ? "bg-zinc-800 text-white rounded-tr-sm" 
                        : "bg-fuchsia-900/20 border border-fuchsia-500/10 text-zinc-200 rounded-tl-sm whitespace-pre-wrap"
                    }`}>
                      {msg.content}
                    </div>
                  </div>
                ))}
                
                {isLoading && (
                  <div className="flex gap-3">
                    <div className="w-8 h-8 rounded-full bg-fuchsia-500/20 flex items-center justify-center shrink-0">
                      <Bot className="w-4 h-4 text-fuchsia-400" />
                    </div>
                    <div className="p-3 rounded-2xl bg-fuchsia-900/20 border border-fuchsia-500/10 rounded-tl-sm flex items-center gap-1">
                      <span className="w-1.5 h-1.5 bg-fuchsia-400 rounded-full animate-bounce [animation-delay:-0.3s]"></span>
                      <span className="w-1.5 h-1.5 bg-fuchsia-400 rounded-full animate-bounce [animation-delay:-0.15s]"></span>
                      <span className="w-1.5 h-1.5 bg-fuchsia-400 rounded-full animate-bounce"></span>
                    </div>
                  </div>
                )}
                {error && (
                  <div className="flex gap-3">
                    <div className="w-8 h-8 rounded-full bg-red-500/20 flex items-center justify-center shrink-0">
                      <Bot className="w-4 h-4 text-red-400" />
                    </div>
                    <div className="p-3 rounded-2xl bg-red-900/20 border border-red-500/10 text-red-200 rounded-tl-sm text-sm break-all">
                      {error}
                    </div>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Input */}
              <form onSubmit={handleSubmit} className="p-3 border-t border-white/10 bg-black/20 flex gap-2">
                <input 
                  type="text" 
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder="Ask about your resilience plan..." 
                  className="flex-1 bg-white/5 border border-white/10 rounded-full px-4 text-sm text-white focus:outline-none focus:border-fuchsia-500 transition-colors"
                />
                <Button type="submit" size="icon" disabled={!(input || "").trim() || isLoading} className="bg-fuchsia-600 hover:bg-fuchsia-700 text-white rounded-full shrink-0">
                  <Send className="w-4 h-4" />
                </Button>
              </form>

            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
